### ISSUE TITLE
request: adjustments to context menu entry

### ISSUE THREAD

**Issue by sebalis** [tiansh/simple-context-search#1]
Thank you so much for this extension. It is exactly what I’ve been looking for: a simple replacement for the standard search entry that uses exactly the search engines defined in the browser without duplicating any information. This is exactly what https://github.com/benbasson/contextsearch used to do for Firefox before the switch to Quantum, and I have been following the development of the required changes to the API but unable to write this extension.

I have two suggestions for the context menu entry you create: it should be next to the standard context search entry in the context menu (which uses the default search engine) and the name of the entry should repeat the currently selected text as the standard entry does. So when the standard entry says “Search [name of default search engine] for “selected text””, your entry should say “Search for “text””. As with the old extension, I would even hide the standard menu entry, although I guess that this might not be possible with the more restrictive Web Extensions API. You will probably need translations for “Search for” and consult the table of typographical quotation marks in the Wikipedia article “quotation mark”. I can give you the German version: Suche nach „text”

Thanks again.

**Comment by tiansh** [comment]
WebExtensions cannot hide predefined menu entries, and cannot chose the position to show the menu item.

Showing only _Search_ instead of _Search for "text"_ is due to:
1. I cannot get the text of clicked link in an elegant way:
    * I have to request permission for _accessing all websites_, which is not what I want;
    * And I still need to inject to each page, and the text can only be updated after the context menu shown ("Search" is first shown, and the changed to "Search for ...").
2. The localized terms is copied from https://transvision.mozfr.org/api/v1/entity/gecko_strings/?id=browser/browser/preferences/preferences.ftl:pane-search-title currently. So I don't need to worry about the localization.

**Comment by sebalis** [comment]
Thanks for responding so quickly and comprehensively. I fully agree with your reasoning under 1, have checked a similar extension that does show the selected text in the context menu and of course you’re correct: it asks for access to all websites. Having accepted that the search text will not be shown, there is of course no text beyond “Search” to localise. I will readjust my expectations. :-) AndI I’m very happy to have this functionality back in a recent Firefox.
