### ISSUE TITLE
搜索设置

### ISSUE THREAD

**Issue by XupingZHENG** [tiansh/simple-context-search#2]
你好，谢谢你做的扩展。
我想问下，这个扩展，能否增删搜索引擎？
还有就是为什么有些搜索引擎后面有数字标号？
![qq 20190208124051](https://user-images.githubusercontent.com/14209404/52459290-48a3ce80-2b9f-11e9-936a-d9e53f818f3c.png)

**Comment by tiansh** [comment]
搜索引擎列表是直接读取的浏览器的。如果需要修改您可以修改浏览器的搜索设置。
数字是因为扩展会自动根据名称首字母给搜索引擎配快捷键，如果搜索引擎的名称没有拉丁字母就只能默认配个数字了。
